### ISSUE TITLE
[LSPlugin Ready Error] TypeError: logseq.useSettingsSchema is not a function

### ISSUE THREAD

**Issue by hiway** [hiway/logseq-plugin-openweather#1]
Works with TypeScript 🤷🏻

**Comment by hankhank10** [comment]
Hello, I'm sorry to post here but I am getting this same error in some code I am writing - and this is the only result anywhere on the internet for this error message!

Could you help guide me as to what I'm doing wrong and how you fixed this? My repo is: [https://github.com/hankhank10/i-listened-plugin](https://github.com/hankhank10/i-listened-plugin)
